#ifndef _STRING_CONSTANTS_H
#define _STRING_CONSTANTS_H
#include <WString.h>

extern const char _OKRESULT[] PROGMEM;
extern const char _ACCESS_CONTROL_HEADER[] PROGMEM;
extern const char _TEXT_PLAIN[] PROGMEM;
extern const char _INVALID_ARGUMENTS[] PROGMEM;
extern const char _HEAP[] PROGMEM;
extern const char _TEMPERATURE[] PROGMEM;
extern const char _VOLTAGE[] PROGMEM;
extern const char _LAST_HTTP_RESPONSE[] PROGMEM;
extern const char _WIFI_AP[] PROGMEM;
extern const char _WIFI_PASSWORD[] PROGMEM;
extern const char _HOSTNAME[] PROGMEM;
extern const char _IPADDRESS[] PROGMEM;
extern const char _DNSSERVER[] PROGMEM;
extern const char _SUBNET[] PROGMEM;
extern const char _GATEWAY[] PROGMEM;
extern const char _UPDATE_INTERVAL[] PROGMEM;
extern const char _INFLUX_HOST[] PROGMEM;
extern const char _INFLUX_PORT[] PROGMEM;
extern const char _INFLUX_USERNAME[] PROGMEM;
extern const char _INFLUX_PASSWORD[] PROGMEM;
extern const char _INFLUX_DATABASE[] PROGMEM;
extern const char _INFLUX_LINE[] PROGMEM;
extern const char _YES[] PROGMEM;
extern const char _NO[] PROGMEM;
extern const char _ERROR_FAILED[] PROGMEM;
extern const char _INFLUX_URL[] PROGMEM;
extern const char _FAILED_TO_READ[] PROGMEM;

#define OKRESULT FPSTR(_OKRESULT)
#define ACCESS_CONTROL_HEADER FPSTR(_ACCESS_CONTROL_HEADER)
#define TEXT_PLAIN FPSTR(_TEXT_PLAIN)
#define INVALID_ARGUMENTS FPSTR(_INVALID_ARGUMENTS)
#define HEAP FPSTR(_HEAP)
#define TEMPERATURE FPSTR(_TEMPERATURE)
#define VOLTAGE FPSTR(_VOLTAGE)
#define LAST_HTTP_RESPONSE FPSTR(_LAST_HTTP_RESPONSE)
#define WIFI_AP FPSTR(_WIFI_AP)
#define WIFI_PASSWORD FPSTR(_WIFI_PASSWORD)
#define HOSTNAME FPSTR(_HOSTNAME)
#define IPADDRESS FPSTR(_IPADDRESS)
#define DNSSERVER FPSTR(_DNSSERVER)
#define GATEWAY FPSTR(_GATEWAY)
#define SUBNET FPSTR(_SUBNET)
#define UPDATE_INTERVAL FPSTR(_UPDATE_INTERVAL)
#define INFLUX_HOST FPSTR(_INFLUX_HOST)
#define INFLUX_PORT FPSTR(_INFLUX_PORT)
#define INFLUX_USERNAME FPSTR(_INFLUX_USERNAME)
#define INFLUX_PASSWORD FPSTR(_INFLUX_PASSWORD)
#define INFLUX_DATABASE FPSTR(_INFLUX_DATABASE)
#define INFLUX_LINE FPSTR(_INFLUX_LINE)

#define YES FPSTR(_YES)
#define NO FPSTR(_NO)
#define ERROR_FAILED FPSTR(_ERROR_FAILED)
#define FAILED_TO_READ FPSTR(_FAILED_TO_READ)

#define INFLUX_URL FPSTR(_INFLUX_URL)

#endif